-- =====================================================================
-- 2026-05-07 — Fuzzy Recommendations + Data Augmentation + Hybrid Forecast
-- =====================================================================
-- This migration adds the tables required for the 3 new academic features:
--   1. Fuzzy logic recommendations (logs of activated rules)
--   2. Multi-source API verification + synthetic data augmentation
--   3. Hybrid ML/DL pollution forecasting with quantitative metrics
--
-- Idempotent: safe to re-run.

-- ----- 1. Fuzzy recommendation logs ------------------------------------
-- Stores every fuzzy-based recommendation computed for a user so we can
-- trace which rules fired (explainability) and what the crisp output was.
CREATE TABLE IF NOT EXISTS fuzzy_reco_logs (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  user_id         INT NULL,
  zone_id         INT NULL,
  pollution       INT NOT NULL,
  vulnerability   INT NOT NULL,            -- 0..10 (sum of weighted flags)
  symptom_sev     INT NOT NULL,            -- 0..10
  alerts_24h      INT NOT NULL,
  age             INT NULL,
  risk_fuzzy      DECIMAL(5,2) NOT NULL,   -- defuzzified centroid 0..100
  urgency_level   ENUM('low','moderate','high','critical') NOT NULL,
  fired_rules     TEXT NULL,               -- JSON list of rule ids + activations
  computed_at     DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_fuzzy_user (user_id),
  KEY idx_fuzzy_at   (computed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----- 2A. API verification log ----------------------------------------
-- Each time an external air-quality API is queried we record raw value,
-- normalized value, outlier flags, and trust score. Lets the admin audit
-- the data pipeline and detect upstream API drifts.
CREATE TABLE IF NOT EXISTS api_verification_log (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  source           VARCHAR(20) NOT NULL,        -- 'iqair' | 'waqi' | 'openaq' | 'fused'
  zone_id          INT NOT NULL,
  raw_value        INT NULL,                    -- as returned by the source
  normalized_value INT NULL,                    -- 0..100 pollution_level scale
  trust_score      DECIMAL(3,2) NOT NULL DEFAULT 1.00,
  flags            VARCHAR(120) NULL,           -- 'range_ok,outlier,cross_ok'
  verified_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_api_zone (zone_id, verified_at),
  KEY idx_api_src  (source, verified_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----- 2B. Augmented (synthetic) historical scores ---------------------
-- Synthetic risk-score points generated by either PHP statistical methods
-- (jittering / time-warping / bootstrap) or a Python TimeGAN/Diffusion
-- pipeline. The forecast trainer reads BOTH real and synthetic data.
CREATE TABLE IF NOT EXISTS risk_scores_augmented (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  zone_id           INT NOT NULL,
  synthetic_at      DATETIME NOT NULL,
  score             INT NOT NULL,
  generation_method ENUM('jitter','magnitude_warp','time_warp','bootstrap',
                         'timegan','tsdiff','csdi','gan_php') NOT NULL,
  generator_version VARCHAR(20) NULL,
  fidelity_score    DECIMAL(3,2) NULL,        -- 0..1 (Wasserstein-derived)
  created_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_aug_zone (zone_id, synthetic_at),
  KEY idx_aug_meth (generation_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- If the table already existed without the 'gan_php' enum value, widen it.
-- (Safe idempotent ALTER for MariaDB / MySQL 5.7+.)
ALTER TABLE risk_scores_augmented
  MODIFY COLUMN generation_method
  ENUM('jitter','magnitude_warp','time_warp','bootstrap',
       'timegan','tsdiff','csdi','gan_php') NOT NULL;

-- ----- 3A. Hybrid ML/DL forecast predictions ---------------------------
-- The hybrid forecaster (PHP AR(7) ensembled with a DL-inspired multi-
-- EWMA-sigmoid; or, if Python is available, XGBoost+LSTM) writes its
-- predictions here. forecast.php prefers the most recent prediction
-- and falls back to the legacy EWMA only when the table is empty.
CREATE TABLE IF NOT EXISTS forecast_predictions (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  zone_id         INT NOT NULL,
  horizon_hours   INT NOT NULL,                -- 6 | 12 | 24
  predicted_score INT NOT NULL,                -- 0..100
  predicted_level ENUM('safe','warning','critical') NOT NULL DEFAULT 'safe',
  method          VARCHAR(50) NOT NULL,        -- 'ensemble_ar_mewma' etc.
  confidence      DECIMAL(3,2) NULL,           -- 0..1
  computed_at     DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_fcst_zone (zone_id, horizon_hours, computed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----- 3B. Forecast model metrics --------------------------------------
-- For every (model, zone, training run) we store the 5 standard error
-- metrics. Admin UI reads this to show the "EWMA vs Hybrid" comparison
-- and prove (numerically) that hybridization wins.
CREATE TABLE IF NOT EXISTS forecast_metrics (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  model_name   VARCHAR(60) NOT NULL,           -- 'ewma','ar7','mewma','ensemble','lstm','xgboost'
  zone_id      INT NULL,                       -- NULL = aggregated across all zones
  mae          DECIMAL(6,3) NULL,
  rmse         DECIMAL(6,3) NULL,
  mape         DECIMAL(6,3) NULL,              -- in percent
  r2           DECIMAL(5,3) NULL,
  smape        DECIMAL(6,3) NULL,              -- in percent
  sample_size  INT NULL,
  trained_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_metric_model (model_name, trained_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----- 3C. WAQI cache (second source for verification) ----------------
CREATE TABLE IF NOT EXISTS waqi_cache (
  zone_id      INT PRIMARY KEY,
  aqi          INT NOT NULL,
  pollution    INT NOT NULL,
  station_name VARCHAR(140) NULL,
  fetched_at   DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
