<?php
/**
 * C12 — Daily environmental & health tips generated by Groq llama-3.1-8b-instant.
 *
 * Endpoint : GET ?lang=en|ar  (default: en)
 * Cache    : 1 row per day × language in `daily_tips`. Regeneration is
 *            automatic if no entry exists for today.
 *
 * Robust : if Groq is unavailable, returns a default localized tip.
 */

require_once __DIR__ . '/../lib/helpers.php';
require_once __DIR__ . '/../lib/auth.php';
require_once __DIR__ . '/../lib/groq_client.php';
require_once __DIR__ . '/../lib/ai_reco.php';   // unified Fuzzy Type-1 + Type-2 + AI engine

$pdo  = db();
$lang = $_GET['lang'] ?? 'en';
if (!in_array($lang, ['en', 'ar'], true)) $lang = 'en';

$today = date('Y-m-d');

/* Cache 24h */
$stmt = $pdo->prepare(
    'SELECT * FROM daily_tips WHERE tip_date = ? AND language = ? LIMIT 1'
);
$stmt->execute([$today, $lang]);
$cached = $stmt->fetch();

if ($cached) {
    json_response([
        'ok'        => true,
        'tip'       => $cached['tip_text'],
        'cached'    => true,
        'date'      => $today,
        'language'  => $lang,
        'context'   => $cached['status_at_gen'],
    ]);
}

/* Real-time context (global status, highest risk zone) */
$status = function_exists('global_status') ? global_status() : 'safe';
$worst  = $pdo->query("
    SELECT z.name, z.status, COALESCE(rs.score, z.pollution_level) AS score
    FROM zones z LEFT JOIN risk_scores rs ON rs.zone_id = z.id
    ORDER BY (z.status='critical') DESC, score DESC LIMIT 1
")->fetch();

$worstName = $worst['name']  ?? '—';
$worstScore = (int)($worst['score'] ?? 0);

/* ---------- Fuzzy backbone: feed today's worst zone into Mamdani ---------- */
$me = function_exists('auth_user') ? auth_user() : null;
$userId = $me ? (int)$me['id'] : 0;
$ai = ai_reco_for_user($pdo, $userId, [
    'pollution' => $worstScore,
    'zone_id'   => isset($worst['id']) ? (int)$worst['id'] : 0,
]);
$fuzzyPrefix = ai_reco_prompt_block($ai);

/* Groq Prompt */
$systemEn = <<<TXT
You are Nafass, the health and environment assistant for Gabès, Tunisia. Generate ONE daily tip
(max 220 characters) that is practical, educational, and adapted to industrial pollution.
No emojis, warm tone. Provide ONE actionable tip.
TXT;

$systemAr = <<<TXT
أنت نفاس، مساعد الصحة والبيئة لمدينة قابس. ولّد نصيحة يومية واحدة
(لا تتجاوز 220 حرفًا) عملية وتعليمية ومناسبة للتلوث الصناعي.
بدون رموز تعبيرية، ولهجة دافئة. أعطِ نصيحة قابلة للتطبيق.
TXT;

$ctxEn = $fuzzyPrefix
       . "Today in Gabès — overall status: $status. Highest risk zone: $worstName ($worstScore/100).\n"
       . "Generate today's tip aligned with the fuzzy risk above.";
$ctxAr = $fuzzyPrefix
       . "اليوم في قابس — الحالة العامة: $status. أكثر منطقة خطرًا: $worstName ($worstScore/100).\n"
       . "ولّد نصيحة اليوم بما يتوافق مع تقييم الخطر الضبابي أعلاه.";

$messages = [
    ['role' => 'system', 'content' => $lang === 'ar' ? $systemAr : $systemEn],
    ['role' => 'user',   'content' => $lang === 'ar' ? $ctxAr   : $ctxEn],
];

$r = groq_chat_call($messages, 'llama-3.1-8b-instant', [
    'temperature' => 0.7,
    'max_tokens'  => 200,
    'timeout'     => 12,
]);

if (!$r['ok']) {
    /* Fallback localized if Groq unavailable */
    $fallback = $lang === 'ar'
        ? "حافظ على ترطيب جسمك واغلق النوافذ خلال ذروة التلوث. اخرج للتنزه في الصباح الباكر إذا كانت الجودة جيدة."
        : "Stay hydrated and close windows during peak pollution hours. Prefer early morning walks when air quality is good.";

    json_response([
        'ok'       => true,
        'tip'      => $fallback,
        'cached'   => false,
        'fallback' => true,
        'error'    => $r['error'],
        'date'     => $today,
        'language' => $lang,
    ]);
}

$tip = trim((string)$r['content']);
$tip = preg_replace('/^["\']|["\']$/u', '', $tip);

/* Store in cache */
try {
    $ins = $pdo->prepare(
        'INSERT INTO daily_tips (tip_date, language, status_at_gen, tip_text)
         VALUES (?, ?, ?, ?)'
    );
    $ins->execute([$today, $lang, $status, $tip]);
} catch (Throwable $e) {
    // possible race condition (two simultaneous requests) — silent fallback
    error_log('[tips] insert: ' . $e->getMessage());
}

json_response([
    'ok'       => true,
    'tip'      => $tip,
    'cached'   => false,
    'date'     => $today,
    'language' => $lang,
    'context'  => $status,
    'fuzzy'    => [
        'risk_score'    => $ai['risk_score'],
        'urgency_level' => $ai['urgency_level'],
        'fired_rules'   => $ai['type1']['fired_rules'],
        'explanation'   => $ai['explanation'],
    ],
    'type2'    => $ai['type2'],
    'model'    => $ai['model'],
]);
